# Generated by Django 3.2 on 2021-11-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0002_alter_boxorder_box_rent_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxorder',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='box.box', verbose_name='бокс'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_orders', to=settings.AUTH_USER_MODEL, verbose_name='арендатор'),
        ),
    ]
