# Generated by Django 3.2 on 2021-11-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20211127_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='box.storage', verbose_name='склад'),
        ),
        migrations.AlterField(
            model_name='box',
            name='things',
            field=models.ManyToManyField(blank=True, related_name='assosiated_boxes', to='box.Thing', verbose_name='вещи'),
        ),
    ]
