# Generated by Django 3.2 on 2021-11-28 07:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20211127_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='телефон склада'),
        ),
    ]
