# Generated by Django 3.2 on 2021-11-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('min_storage_time', models.PositiveIntegerField(verbose_name='минимальное время хранения, сут.')),
                ('max_storage_time', models.PositiveIntegerField(verbose_name='максимальное время хранения, сут.')),
                ('storage_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='стоимость за минимальное время хранения')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seasonal_keeping.thing')),
            ],
        ),
    ]
