# Generated by Django 3.2 on 2021-11-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_keeping', '0001_create_two_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seasonal_keeping.thing', verbose_name='относится к вещи'),
        ),
    ]
