# Generated by Django 3.2 on 2021-11-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasonal_keeping', '0002_add_field_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='ул. Манчестерская, д. 7, кв. 1', verbose_name='адрес')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.place', verbose_name='расположено по адресу')),
                ('alias', models.CharField(max_length=128, verbose_name='запоминающееся название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='стоимость аренды за 1 кв.м.')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.ManyToManyField(blank=True, related_name='assosiated_boxes', to='seasonal_keeping.Thing', verbose_name='находится вещь')),
                ('storages', models.ManyToManyField(blank=True, related_name='boxes', to='core.Storage', verbose_name='является частью склада')),
            ],
        ),
    ]
